exports.DARK_THEME='dark';
exports.LIGHT_THEME='light';
exports.NAVS = ['home', 'about', 'projects', 'experience', 'contact'];
exports.TITLES = ['Full Stack Development', 'Mern Stack Development'];
exports.SHORT_DESCRIPTION= 'I am a Computer Science Engineer passionate in building web applications that can scale. I am deeply passionate about learning system design and core computer fundamentals.'
exports.NAME='Sai Mounika Peri',
exports.ABOUT_IMAGE_CAPTION = '< I build stuff 🚀/>'
exports.TITLE = 'Full Stack Developer';
exports.ABOUT = 'I am a full stack developer passionate in building systems that scale. I am currently working at Cognizant as a Full Stack Developer having 5+ years of experience in FullStack and MernStack. I am passionate building and scaling web applications and learning system design and computer core fundamentals. I hold AWS certifications. I keep publishing articles and blogs on HashNode. Reading and Implementing bunch of research papers and Reading few of engineering books every now and then.';
exports.RESUME_URL = 'resumeurl';
exports.CALL_URL='callurl';