exports.DARK_THEME='dark';
exports.LIGHT_THEME='light';
exports.NAVS = ['home', 'about', 'projects', 'experience', 'contact'];
exports.TITLES = ['Full Stack Development', 'Mern Stack Development'];
exports.TECH_STACKS = ['Full-Stack', 'Mern-Stack', 'Basic Web'];
exports.TECH_CATEGORIES = ['BackEnd', 'FrontEnd', 'Basic Web'];
exports.KNOWLEDGE_SECTION= ['Experiences', 'Education', 'Certifications'];
exports.SHORT_DESCRIPTION= 'I am a Full Stack Developer with a passion for building and scaling systems. Currently working at Cognizant, I have 5+ years of experience in Full Stack and MERN Stack development. I specialize in building scalable applications and designing event-driven architectures, seamlessly integrating multiple microservices.'
exports.NAME='Sai Mounika Peri';
exports.ABOUT_IMAGE_CAPTION = '< I build stuff 🚀/>'
exports.TITLE = 'Full Stack, Mern Stack Developer';
exports.ABOUT = 'I am a Full Stack Developer with a passion for building and scaling systems. Currently working at Cognizant, I have 5+ years of experience in Full Stack and MERN Stack development. I specialize in building scalable applications and designing event-driven architectures, seamlessly integrating multiple microservices. I have played a key role in optimizing backend processes. Additionally, I am proficient in designing and deploying cloud-based solutions, leveraging AWS services to enhance system efficiency and scalability. Beyond development, I hold AWS certifications. I am deeply interested in system design, core computer science fundamentals, and continuously explore research papers and engineering books to refine my knowledge.';
exports.RESUME_URL = 'resumeurl';
exports.CALL_URL='callurl';